sonar.projectKey=Pw
sonar.host.url=http://localhost:9000
sonar.token=sqp_d41a4e650298cbfaa33774ccb81797a4715a0dd4
sonar.sources=.
sonar.exclusions=node_modules/**,test-results/**,playwright-report/**
sonar.typescript.tsconfigPath=tsconfig.json